services:
  - type: web
    name: ashish-portfolio
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: "/"

    # Environment variables - set these in the Render dashboard
    # GMAIL_USER: your_email@gmail.com
    # GMAIL_APP_PASSWORD: your_app_password